### PR TITLE
Mark all as read function

### PR DESCRIPTION
**Pull request by filipeotero**
This PR implements the subscriptions to the button of the 'Mark All As Read' functionality. 

FYI: @QilongTang @reddyashish @zeusongit @RobertGlobant20 @jesusalvino

### CODE REVIEW

**Review by reddyashish — APPROVED** [review]

**Comment by filipeotero** [comment]
Hi @avidit, the build is crashing because of the 'chrome' term that is used to call a Dynamo method. Is there a way to fix this?

**Comment by avidit** [comment]
> Hi @avidit, the build is crashing because of the 'chrome' term that is used to call a Dynamo method. Is there a way to fix this?

Please add `"webextensions": true` under `env` in [.eslintrc](https://github.com/DynamoDS/NotificationCenter/blob/master/.eslintrc#L2)

**Review by QilongTang — COMMENTED** [review]
Can you bump up the version? Otherwise, LGTM

**Comment by QilongTang** [comment]
Thank you @filipeotero Once the version here is bumped, will merge

**Review by QilongTang — APPROVED** [review]

**Pull request merged**
